
export const DEFAULT_NUTRI_PROFILE = [
    {
        name: 'Méditéranéen', 
        description: 'Riche en légumes, fruits, grains entiers, huile d’olive, légumineuses, noix, graines, poisson et fruits de mer, le régime méditerranéen fait place à la volaille, aux œufs et aux produits laitiers. Il est pauvre en viande rouge et en aliments sucrés.',
        forbidden_foods: ['Sucre', 'Viande rouge'],
        checked: false, 
        is_starter: true,
        visited_cafes: [],
        desired_foods: [],
    },
  
    {
        name: 'Végétarisme', 
        description: 'Le végétarisme est une pratique alimentaire qui exclut la consommation de chair animale. Elle est associée à la cuisine végétarienne.',
        forbidden_foods: ['Viande', 'Poisson', 'Fruits de mer'],
        checked: false, 
        is_starter: true, 
        visited_cafes: [],
        desired_foods: ["Legumes", "Fruits"],
    },
  
    {
        name: 'Cétogène', 
        description: 'La diète cétogène, souvent utilisée dans un contexte de perte de poids, est un régime faible en glucides et élevé en gras.',
        forbidden_foods: ['Sucre', 'Légume', 'Alcool'], 
        checked: false, 
        is_starter: true, 
        visited_cafes: [], 
        desired_foods: [],
    },
];

export const ALLERGENS_LIST = [
    'Lactose', 'Oeuf', 'Poisson', 'Crustacés', 'Cacahuètes', 'Soja', 'Sésame', 'Moutarde', 'Celery',
];

export const NUTRI_PREFERENCES_LIST = [
    { name: "Calories", value: null },
    { name: "Protéines", value: null },
    { name: "Glucides", value: null },
    { name: "Lipides", value: null },
    { name: "Gras saturés", value: null },
    { name: "Sodium", value: null },
    { name: "Sucre", value: null },
    { name: "Fibres", value: null },
    { name: "Zinc", value: null },
    { name: "Fer", value: null },
    { name: "Calcium", value: null },
    { name: "Magnésium", value: null },
    { name: "Potassium", value: null },
    { name: "Vitamine A", value: null },
    { name: "Vitamine C", value: null },
    { name: "Vitamine D", value: null },
    { name: "Vitamine E", value: null },
    { name: "Vitamine K", value: null },
    { name: "Vitamine B6", value: null },
    { name: "Vitamine B12", value: null },

];

export const NUTRI_PREFERENCES_LIST_EN = [
    { name: "calories", value: null },
    { name: "proteins", value: null },
    { name: "carbohydrates", value: null },
    { name: "lipids", value: null },
    { name: "saturated_fat", value: null },
    { name: "sodium", value: null },
    { name: "sugar", value: null },
    { name: "fiber", value: null },
    { name: "zinc", value: null },
    { name: "iron", value: null },
    { name: "calcium", value: null },
    { name: "magnesium", value: null },
    { name: "potassium", value: null },
    { name: "vitamina", value: null },
    { name: "vitaminc", value: null },
    { name: "vitamind", value: null },
    { name: "vitamine", value: null },
    { name: "vitamink", value: null },
    { name: "vitaminb6", value: null },
    { name: "vitaminb12", value: null },

];

export const NUTRI_NAME_CONVERTER_FR_TO_EN = {
    "Zinc": "zinc",
    "Fer": "iron",
    "Calcium": "calcium",
    "Magnésium": "magnesium",
    "Potassium": "potassium",
    "Vitamine A": "vitamina",
    "Vitamine C": "vitaminc",
    "Vitamine D": "vitamind",
    "Vitamine E": "vitamine",
    "Vitamine K": "vitamink",
    "Vitamine B6": "vitaminb6",
    "Vitamine B12": "vitaminb12",   
    "Calories": "calories",   
    "Lipides": "lipids",   
    "Protéines": "proteins",   
    "Glucides": "carbohydrates",   
    "Sucre": "sugar",   
    "Sodium": "sodium",   
    "Fibres": "fiber",   
    "Gras saturés": "saturated_fat",
};
 
export const NUTRI_NAME_CONVERTER_EN_TO_FR = {
    "zinc": "Zinc",
    "iron": "Fer",
    "calcium": "Calcium",
    "magnesium": "Magnésium",
    "potassium": "Potassium",
    "vitamina": "Vitamine A",
    "vitaminc": "Vitamine C",
    "vitamind": "Vitamine D",
    "vitamine": "Vitamine E",
    "vitamink": "Vitamine K",
    "vitaminb6": "Vitamine B6",
    "vitaminb12": "Vitamine B12",
    "calories": "Calories",
    "lipids": "Lipides",
    "proteins": "Protéines",
    "carbohydrates": "Glucides",
    "sugar": "Sucre",
    "sodium": "Sodium",
    "fiber": "Fibres",
    "saturated_fat": "Gras saturés",
};