@startuml CU
left to right direction
actor gerant as g
actor employe as em

package systeme{
    usecase " voir horaire du cafe" as CU1
    usecase "voir evenement " as CU2
    usecase "ajouter un evenement " as CU3
    usecase "retirer un evenement " as CU4
    usecase "ajouter  benevole a l'hoiraire" as CU4
    usecase "retirer  benevole de l'hoiraire" as CU5
    usecase "communiquer avec les benevoles" as CU6
    usecase "ajouter  benevole au systeme" as CU7
    usecase "donner des droits au bevenoles" as CU8
    usecase "clock In" as CU9
    usecase "voir mon horaire" as CU10
}

em --> CU9
em --> CU10

g --> CU1
g --> CU2
g --> CU3
g --> CU4
g --> CU5
g --> CU6
g --> CU7
g --> CU8
@enduml
