@startuml class diagram
left to right direction 



class Cafe {
    {static} + name:String
    {static} + location:String

    
    + GetVolunteers():List<Volunteer>
    + addNewVolunteer(v:Volunteer):void
    + removeVoLunteer(v:Volunteer):void
    
    + assignShift(v:Volunteer):void
    + addNewProduct():void
    + viewStock():void 
    + printStock():void
}

class WorkerService {
    {static} + getVolunteers():List<Volunteer>
    {static} + addNewVolunteer(v:Volunteer):string
    {static} + removeVoLunteer(v:Volunteer):string
    {static} + assignShift(v:Volunteer):string
    {static} + updateVolunteer(v:Volunteer):string
    {static} + updateManager(m:Manager):string
}

class ProductService {
    {static} + getProducts():List<Products>
    {static} + addNewProduct(v:Product):string
    {static} + removeProduct(v:Product):string

}

class PlannerService {
    {static} + getShifts():List<Shift>
    {static} + addNewShift(v:Shift, User:User):string
    {static} + getEvents():List<Event>
    {static} + addNewEvent(v:Event):string
    {static} + getEvent(e:Event):Event
}
class Worker{
    - name:String
    - cafe:cafe
    - shift:Shift

    + seeShift():Shift

}
class Manager{
    

    
    
    
}

class Volunteer{
   



}

class Product {
    - ID:Int 
    - name:string
    - price:float
    - Description:string 
    
    + toString():String 
    + getID() :Int 

}



class Shift{
   
}

class Event {
   
}

class Plan{

     - date:Date
    - startTime:Time
    - endTime:Time
    - name:String

    +getDate():Date
    +getstartTime():Time
    +getEndTime():Time
    +getName() :String
    +toString():String

}

class Planner{
    events:List<Plans>
    shifts:List<Plans>
    + addEvent():void 
    + removeEvent():void
    + getEvents():List<Event>
    + etEvents():List<Shift>
    + addNewVolunteer(v:Volunteer):void
    + removeVoLunteer(v:Volunteer):void

}

class WokerController{
    {static} + volunteers: List<Volunteer>
    {static} + manager:Manager


}

class PlannerController{
    {static} + plans:List<Plans>
    {static} + assignShift(v:Volunteer):void

}

class ProductController{
    {static} + products:List<Product>
    {static} + addNewProduct():void
    {static} + viewStock():void 
    {static}  + printStock():void

}





Cafe "1" -- "1" PlannerController

Worker "1" o--right-- "1..*" Plan:has




Worker "1" -- "1..*" Worker:Manages



ProductController "1" *-up- "1..*" Product:contain 
ProductController "1" -up- "1..*" ProductService
Cafe  "1" -left- "1..*" ProductController


Volunteer -left-^ Worker
Manager -left--^ Worker


WokerController "1" -- "1" Worker
WokerController "1" -- "1" Cafe
WokerController "1" -up- "1" WorkerService:communicates

PlannerController "1" -right- "1" PlannerService:communicates



Plan ^-right- Shift
Plan ^-right- Event

Plan "1..*" --o "1" Planner:includes

PlannerController  "1" *-- "1..*" Plan 

@enduml

