@startuml class diagram
left to right direction 



class Cafe {
    {static} + name:String
    {static} + location:String

    
    + GetVolunteers():List<Volunteer>
    + addNewVolunteer(v:Volunteer):void
    + removeVoLunteer(v:Volunteer):void
    + printStock():void
    + addNewVolunteer(v:Volunteer):void
    + removeVoLunteer(v:Volunteer):void
    + assignShift(v:Volunteer):void
    + addNewProduct():void
    + viewStock():void 
}

class WorkerService {
    {static} + getVolunteers():List<Volunteer>
    {static} + addNewVolunteer(v:Volunteer):string
    {static} + removeVoLunteer(v:Volunteer):string
    {static} + assignShift(v:Volunteer):string
    {static} + updateVolunteer(v:Volunteer):string
    {static} + updateManager(m:Manager):string
}

class ProductService {
    {static} + getProducts():List<Products>
    {static} + addNewProduct(v:Product):string
    {static} + removeProduct(v:Product):string

}

class PlannerService {
    {static} + getShifts():List<Shift>
    {static} + addNewShift(v:Shift, User:User):string
    {static} + getEvents():List<Event>
    {static} + addNewEvent(v:Event):string
    {static} + getEvent(e:Event):Event
}
class Worker{
    - name:String
    - cafe:cafe
    - shift:Shift

    + seeShift():Shift

}
class Manager{
    

    
    
    
}

class Volunteer{
   



}

class Product {
    - ID:Int 
    - name:string
    - price:float
    - Description:string 
    
    + toString():String 
    + getID() :Int 



}



class Shift{
    - date:Date
    - startTime:Time 
    - endTime:Time

     +getDate():Date
     +getstartTime():Time
     +getEndTime():Time
     +toString():String
}

class Event {
    - date:Date
    - startTime:Time
    - endTime:Time
    - name:String

    +getDate():Date
    +getstartTime():Time
    +getEndTime():Time
    +getName() :String
    +toString():String
}

class Planner{
    events:List<Event>
    shifts:List<Shift>

    + addEvent():void 
    + removeEvent():void
    +getEvents():List<Event>
    +getEvents():List<Shift>

}

class WokerController{
    {static} + volunteers: List<Volunteer>
    {static} + manager:Manager


}

class PlannerController{
    {static} + shifts:List<Shifts>
    {static} + Events:List<Events>

}

class ProductController{
    {static} + products:List<Product>

}

Event "1..*" --o "1" Planner:includes
Shift "1..*" --o "1" Planner:includes

PlannerController "1" -- "1..*" Event:creates
Cafe "1" -- "1" PlannerController

Worker "1" o--right-- "1..*" Shift:has
Volunteer "1" -up- "1..*" Shift



Worker "1" -- "1..*" Worker:Manages



ProductController "1" *-up- "1..*" Product:contain 
ProductController "1" -up- "1..*" ProductService
Cafe  "1" -left- "1..*" ProductController



Manager -up-^ Worker
Volunteer --^ Worker

WokerController "1" -left- "1" Worker
WokerController "1" -- "1" Cafe
WokerController "1" -left- "1" WorkerService:communicates

PlannerController "1" -right- "1" PlannerService:communicates
PlannerController "1" *-- "1..*" Shift

@enduml

