name: Deploy Front-end

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - preview

jobs:
  deploy-front:
    name: Deploy Front-end
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps: 
      - name: Deploy Front-end to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.FRONTEND_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
